# Generated by Django 5.0.1 on 2025-12-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_family_student_family_signeddocument'),
        ('lessons', '0002_lesson_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgoal',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to='core.teacher'),
        ),
    ]
