# Generated by Django 5.0.1 on 2025-12-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_instrument'),
        ('lessons', '0003_alter_studentgoal_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.band'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.student'),
        ),
    ]
