# Generated by Django 5.0.1 on 2025-12-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('lessons', '0004_lesson_band_alter_lesson_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='inventory.practiceroom'),
        ),
    ]
