# Generated by Django 5.0.1 on 2026-02-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_lesson_lesson_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonplan",
            name="difficulty_level",
        ),
    ]
