# Generated by Django 5.0.1 on 2026-03-05 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_remove_lessonplan_difficulty_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCalendarFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this calendar", max_length=200),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for the calendar overlay (e.g. #6366f1)",
                        max_length=7,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="When disabled, events are hidden from the schedule"
                    ),
                ),
                ("url", models.URLField(help_text="iCal (.ics) feed URL", max_length=2000)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last fetch error message, if any"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_calendar_feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "external_calendar_feeds",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExternalCalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("uid", models.CharField(max_length=500)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("start_dt", models.DateTimeField()),
                ("end_dt", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="lessons.externalcalendarfeed",
                    ),
                ),
            ],
            options={
                "db_table": "external_calendar_events",
                "ordering": ["start_dt"],
                "indexes": [
                    models.Index(
                        fields=["feed", "start_dt"], name="external_ca_feed_id_b1fa96_idx"
                    ),
                    models.Index(
                        fields=["start_dt", "end_dt"], name="external_ca_start_d_39094a_idx"
                    ),
                ],
                "unique_together": {("feed", "uid")},
            },
        ),
    ]
