# Generated by Django 5.0.1 on 2025-12-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_student_invoice_teacher_alter_invoice_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
