# Generated by Django 5.0.1 on 2025-12-19 11:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('audio', 'Audio File'), ('video', 'Video File'), ('image', 'Image'), ('physical', 'Physical Item'), ('link', 'External Link'), ('other', 'Other')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('external_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_physical_item', models.BooleanField(default=False)),
                ('quantity_total', models.IntegerField(default=1)),
                ('quantity_available', models.IntegerField(default=1)),
                ('is_lendable', models.BooleanField(default=False)),
                ('checkout_duration_days', models.IntegerField(default=14)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with_students', models.ManyToManyField(blank=True, related_name='shared_resources', to='core.student')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.studio')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('checked_out', 'Checked Out'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='checked_out', max_length=20)),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='resources.resource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_checkouts', to='core.student')),
            ],
            options={
                'db_table': 'resource_checkouts',
                'ordering': ['-checked_out_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_resourc_dcd1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['studio', 'is_public'], name='resources_studio__3eee1e_idx'),
        ),
    ]
