# Generated by Django 5.0.1 on 2026-02-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_band_photo_alter_studio_cover_image_and_more"),
        ("resources", "0002_resource_file_upload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="band",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this resource belongs to a specific band/group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="core.band",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload files (PDFs up to 10MB, media files up to 50MB)",
                null=True,
                upload_to="resources/%Y/%m/",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["band"], name="resources_band_id_dd9b34_idx"),
        ),
    ]
