# Generated by Django 5.0.1 on 2026-02-04 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_band_photo_alter_studio_cover_image_and_more"),
        ("resources", "0003_resource_band_alter_resource_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="composer",
            field=models.CharField(blank=True, help_text="Composer/Artist name", max_length=200),
        ),
        migrations.AddField(
            model_name="resource",
            name="instrument",
            field=models.CharField(
                blank=True,
                help_text="Primary instrument (Piano, Guitar, Drums, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="key_signature",
            field=models.CharField(
                blank=True, help_text="Musical key (C, G, Am, etc.)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="skill_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("professional", "Professional"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tempo",
            field=models.CharField(blank=True, help_text="Tempo marking or BPM", max_length=50),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("audio", "Audio File"),
                    ("video", "Video File"),
                    ("image", "Image"),
                    ("physical", "Physical Item"),
                    ("link", "External Link"),
                    ("sheet_music", "Sheet Music"),
                    ("chord_chart", "Chord Chart"),
                    ("tablature", "Tablature"),
                    ("lyrics", "Lyrics"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["instrument"], name="resources_instrum_c0fb38_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["skill_level"], name="resources_skill_l_552918_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type", "instrument"], name="resources_resourc_8ee64a_idx"
            ),
        ),
    ]
