# Generated by Django 5.0.1 on 2026-02-05 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_band_photo_alter_studio_cover_image_and_more'),
        ('resources', '0004_songbook_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_setlists', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='core.studio')),
            ],
            options={
                'db_table': 'resource_setlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetlistResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.setlist')),
            ],
            options={
                'db_table': 'resource_setlist_resources',
                'ordering': ['order'],
                'unique_together': {('setlist', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='setlist',
            name='resources',
            field=models.ManyToManyField(related_name='setlists', through='resources.SetlistResource', to='resources.resource'),
        ),
        migrations.AlterUniqueTogether(
            name='setlist',
            unique_together={('studio', 'name')},
        ),
    ]
