# Generated by Django 5.0.1 on 2026-02-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_setlist_setlistresource_setlist_resources_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="resource",
            name="resources_skill_l_552918_idx",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="skill_level",
        ),
    ]
