# Generated by Django 5.0.1 on 2026-02-26 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_student_skill_level"),
        ("resources", "0006_remove_resource_resources_skill_l_552918_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent folder. Null means this is a root-level folder.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="resources.resourcefolder",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_folders",
                        to="core.studio",
                    ),
                ),
            ],
            options={
                "db_table": "resource_folders",
                "ordering": ["name"],
                "unique_together": {("studio", "parent", "name")},
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Virtual folder this resource belongs to. Null = root level.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="resources.resourcefolder",
            ),
        ),
    ]
