# Generated by Django 5.0.1 on 2025-12-21 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('lesson_scheduled', 'Lesson Scheduled'), ('lesson_reminder', 'Lesson Reminder'), ('lesson_cancelled', 'Lesson Cancelled'), ('new_student', 'New Student'), ('new_message', 'New Message'), ('payment_received', 'Payment Received'), ('payment_due', 'Payment Due'), ('document_pending', 'Document Pending Signature'), ('document_signed', 'Document Signed'), ('system_update', 'System Update'), ('inventory_request', 'Inventory Request'), ('room_reserved', 'Practice Room Reserved')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Internal app link', max_length=500, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_lesson_id', models.IntegerField(blank=True, null=True)),
                ('related_student_id', models.IntegerField(blank=True, null=True)),
                ('related_message_id', models.IntegerField(blank=True, null=True)),
                ('related_document_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx')],
            },
        ),
    ]
