# Generated by Django 5.0.1 on 2025-12-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('lesson_scheduled', 'Lesson Scheduled'), ('lesson_reminder', 'Lesson Reminder'), ('lesson_cancelled', 'Lesson Cancelled'), ('new_student', 'New Student'), ('new_message', 'New Message'), ('payment_received', 'Payment Received'), ('payment_due', 'Payment Due'), ('document_pending', 'Document Pending Signature'), ('document_signed', 'Document Signed'), ('system_update', 'System Update'), ('inventory_request', 'Inventory Request'), ('room_reserved', 'Practice Room Reserved'), ('instructor_request', 'Instructor Role Request')], max_length=50),
        ),
    ]
