# Generated by Django 5.0.1 on 2025-12-20 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_parent_families', to=settings.AUTH_USER_MODEL)),
                ('secondary_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_parent_families', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='core.studio')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'db_table': 'families',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.family'),
        ),
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('liability_waiver', 'Liability Waiver'), ('media_release', 'Media Release'), ('policy_agreement', 'Studio Policy Agreement'), ('other', 'Other')], max_length=50)),
                ('content_snapshot', models.TextField(help_text='Copy of the text agreed to')),
                ('signature_image', models.FileField(upload_to='signatures/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to='core.family')),
                ('signer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to='core.student')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to='core.studio')),
            ],
            options={
                'db_table': 'signed_documents',
                'ordering': ['-signed_at'],
            },
        ),
    ]
