# Generated by Django 5.0.1 on 2025-12-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_family_student_family_signeddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='band',
        ),
        migrations.AddField(
            model_name='student',
            name='bands',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.band'),
        ),
    ]
