# Generated by Django 5.0.1 on 2025-12-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_band_student_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='band',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
