# Generated by Django 5.0.1 on 2025-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_band_genre_band_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bands/'),
        ),
    ]
