# Generated by Django 5.0.1 on 2025-12-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_band_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='layout_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
