# Generated by Django 5.0.1 on 2025-12-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studio_layout_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='instrument',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
