# Generated by Django 5.0.1 on 2026-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_setup_wizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='studio_covers/'),
        ),
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
    ]
