# Generated by Django 5.0.1 on 2026-02-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_studio_cover_image_delete_featureflag"),
    ]

    operations = []
