# Generated by Django 5.0.1 on 2026-02-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_band_photo_alter_studio_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="skill_level",
        ),
    ]
