# Generated by Django 5.0.1 on 2026-03-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_studio_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="instruments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
