# Generated by Django 5.0.1 on 2026-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_student_instruments"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
